mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import searcher

urlpatterns = patterns('',
	url(r'^', include('searcher.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

mysite/searcher/urls.py
from django.conf.urls import patterns, url, include
from searcher import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns('',
	url(r'^account/(?P<username>\S+)$', 'searcher.views.account_lookup'),

	url(r'^close-account/$', 'searcher.views.close_account_form', name='close_account'),

	url(r'^transfer/$', 'searcher.views.transfer_money_form', name='transfer_money'),

    url(r'^$', 'searcher.views.login_user'),

	url(r'^login/$', 'searcher.views.login_user'),
)
	

mysite/searcher/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from datetime import datetime
from django.db.models.signals import pre_save
from django.dispatch import receiver

class User(models.Model):
	name = models.CharField(max_length=256, default = 0)
	address = models.CharField(max_length=256, default = 0)
	birthday = models.CharField(max_length=256, default=0)
	email = models.CharField(max_length=256, default = 0)

class UserProfile(models.Model):
	user = models.ForeignKey(User)

class CorporateUser(models.Model):
	profile = models.ForeignKey(UserProfile)


class IndividualUser(models.Model):
	profile = models.ForeignKey(UserProfile)


class CheckingsAccount(models.Model):
	user = models.ForeignKey(User)
	amount = models.DecimalField(default = 0, max_digits=10, decimal_places=2)

class SavingsAccount(models.Model):
	user=models.ForeignKey(User)
	amount = models.DecimalField(default = 0, max_digits=10, decimal_places=2)


class TransactionBarcodeSeq(models.Model):
	placeholder = models.CharField(max_length=8)

class CheckingsTransaction(models.Model):
	account = models.ForeignKey(CheckingsAccount)
	date = models.DateTimeField(auto_now_add=True)
	amount_moved = models.DecimalField(default=0, max_digits=10, decimal_places=2)
	description = models.CharField(max_length=256, default=0)
	barcode = models.CharField(max_length = 8)


class SavingsTransaction(models.Model):
	account = models.ForeignKey(SavingsAccount)
	date = models.DateTimeField(auto_now_add=True)
	amount_moved = models.DecimalField(default=0, max_digits=10, decimal_places=2)
	description = models.CharField(max_length=256, default=0)
	barcode = models.CharField(max_length = 8)


@receiver(pre_save, sender=CheckingsTransaction)
def get_checkings_transaction_barcode(sender, instance, *args, **kwargs):
  if instance.barcode == '':                                                          
    seq = TransactionBarcodeSeq.objects.create()                            
    instance.barcode = "BCT{0:05d}".format(seq.id)

@receiver(pre_save, sender=SavingsTransaction)
def get_savings_transaction_barcode(sender, instance, *args, **kwargs):
  if instance.barcode == '':                                                          
    seq = TransactionBarcodeSeq.objects.create()                            
    instance.barcode = "BST{0:05d}".format(seq.id)


class CloseAccountRequest(models.Model):
	account_holder = models.CharField(max_length=256, default=0)
	debit_credit = models.CharField(max_length=256, default = 0)
	reason = models.CharField(max_length=256, default=0)
	date_requested = models.DateTimeField(auto_now_add=True)


class CloseAccountForm(forms.Form):
	account_holder = forms.CharField(max_length=256)
	debit_credit = forms.CharField(max_length=256)
	reason = forms.CharField(max_length=256)

class TransferMoneyForm(forms.Form):
	account_holder = forms.CharField(max_length=256)
	debit_credit = forms.CharField(max_length=256)
	reason = forms.CharField(max_length=256)
	amount_transfer = forms.DecimalField(max_digits=10, decimal_places=2)
	routing_number = forms.CharField(max_length=256)

mysite/searcher/views.py
from django.core import serializers
from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from django.http import *
from django.template import RequestContext, loader
from django.views.decorators.csrf import csrf_exempt
from django.db import connection, transaction
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

from django.views import generic

import psycopg2
import psycopg2.extras

from searcher.models import *

import json
import simplejson

import operator
import decimal
import datetime


class DecimalJSONEncoder(simplejson.JSONEncoder):
    def default(self, o):
    	if hasattr(o, 'isoformat'):
           return o.isoformat()
        elif isinstance(o, decimal.Decimal):
            return str(o)
        return o.__dict__


def login_user(request):
	logout(request)
	username = password = ''
	
	if request.POST:
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		
		if user is not None:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect('/account/' + username)
	
	return render_to_response('searcher/login.html', context_instance=RequestContext(request))


@login_required(login_url='/login/')
def account_lookup(request, username):
	if request.is_ajax():
		envelope = {}

		try:
			user = list(User.objects.filter(username=username).values())
			checkings_account = list(user[0].CheckingsAccount.all())
			savings_account = list(user[0].SavingsAccount.all())

		except IndexError:
			envelope = {
				'status': 0,
				'message': 'not found'
			}

		else:

			data = {
				'user': user,
				'account': checkings_account,
				'account1': savings_account,
			}

			envelope = {
				'status': 1,
				'message': "1 okay",
				'data': data
			}

		return HttpResponse(simplejson.dumps(envelope, cls=DecimalJSONEncoder), content_type='application/json')

	else:	
		return render(request, 'searcher/account.html', {"username": username})

def close_account_form(request):
	if request.method == 'POST':
		form = CloseAccountForm(request.POST)

		print form

		if form.is_valid():

			print "Close account form is valid!"

			account_holder = form.cleaned_data['account_holder']
			debit_credit = form.cleaned_data['debit_credit']
			reason = form.cleaned_data['reason']

			account_close_request(account_holder, debit_credit, reason)

			return HttpResponse("Account closure request sent to banker. Account will close within 1 business day.")
	
	else: 
		form = CloseAccountForm()

	return render(request, 'searcher/close-form.html', {'form': form})


# Transfer Money form
# Tony 11/17/2014
def transfer_money_form(request):
	if request.method == 'POST':
		form = TransferMoneyForm(request.POST)

		print form

		if form.is_valid():

			print "Transfer form is valid!"

			account_holder = form.cleaned_data['account_holder']
			debit_credit = form.cleaned_data['debit_credit']
			reason = form.cleaned_data['reason']
			amount_transfer = form.cleaned_data['amount_transfer']
			routing_number= form.cleaned_data['routing_number']

			user_giving = Account.objects.filter(barcode=account_holder).get()
			user_receiving = Account.objects.filter(barcode=routing_number).get()

			user_giving_new_amount = user_giving.amount - amount_transfer

			# checking if the user who wants to transfer money has enough
			if user_giving_new_amount < 0:
				return HttpResponse("insufficient funds. Please place more money in account or transfer less")

			user_receiving_new_amount = user_receiving.amount + amount_transfer

			# updating new values after successful transfer
			user_giving.amount = user_giving_new_amount
			user_receiving.amount = user_receiving_new_amount

			user_giving.save()
			user_receiving.save()

			return HttpResponse("Money successfully transferred")
	
	else: 
		form = TransferMoneyForm()

	return render(request, 'searcher/transfer-form.html', {'form': form})

mysite/searcher/templates/searcher/account.html
{% load jstemplate %}
{% load staticfiles %}
<!DOCTYPE html>
<html>


<link href="{% static 'dist/css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'dist/css/Custom.css' %}" rel="stylesheet">
<script src="https://code.jquery.com/jquery.js"></script>
<script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'libs/mustache.js' %}"></script>
<script type="text/javascript">
  		Mustache.tags = ['[[', ']]'];


    	function get_account(barcode){

    		$.ajax({
				dataType: "json",
				url: "/account/" + barcode,
				data: {},
				envelope: {},

				success: function(res) {

					console.log(res);

					// Have all available data
					if ( res.status === 1 ) {

	                    account_data = res.data;

						console.log("found results")
						console.log(res.data);
						var template = $('#account-template').html();
						var html = Mustache.to_html(template,res.data);
						console.log(html);
						$('#dynamic-area').html(html);

                        // Added by Huandari to display on available account
                        var accountType = res.data.account[0].debit_credit;
                        if (accountType == "credit")
                        {
                            $('#creditSummaryRow').show();
                            $('#debitSummaryRow').hide();
                            $('#totalSummaryRow').show();
                        }
                        else if (accountType == "debit")
                        {
                            $('#creditSummaryRow').hide();
                            $('#debitSummaryRow').show();
                            $('#totalSummaryRow').show();
 
                        }

						// fill in the graph data
	                    //var ctx = $(".cpd_abundance").get(0).getContext("2d");
	                    //var cpd_chart = new Chart(ctx).Bar(graph_data);

					}


					// No data at all for that fraction
					else {
						var template = $('#no-results-template').html();
						console.log(template);
						var html = Mustache.to_html(template);
						console.log(html);
						$('#dynamic-area').html(html);
					}

				}

			});
		}

</script>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django Unchained Banking App</title>
</head>

<body>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="col-md-10"
            style="padding-left:0px;padding-top:10px;padding-bottom:10px;">
                <img 
                src="{% static 'dist/images/logo.jpg' %}"
                style = "height: 50px; width: 50px;"></img>
                <h3 style="display:inline;padding-left: 5px;">Django Unchained</h3>
            </div>
        </div>
    </div>
    <div class="row">
            <div class="col-sm-8 col-md-8 col-md-offset-2">
                <nav class="navbar navbar-default" role="navigation">
                    <ul class="nav nav-justified navbar-nav">
                        <li class="active"><a href="#">Summary</a></li>
                        <li><a href="#">Transactions</a></li>
                        <li><a href="#">Settings</a></li>
                    </ul>
                </nav>
            </div>
    </div>

    <script id="account-template" type="text/template">
            [[#user]]
            <div class="row">
                <div class="col-sm-8 col-md-8 col-md-offset-2">
                    <h3>Welcome back, [[name]].</h3>
                    <br>
                    <h5>[[email]]</h5>
                    <h5>[[address]]</h5>
                    <br>
                    <h4>Here is your account summary:</h4>
                </div>
            </div>
            [[/user]]

            <br>

                [[#account]]
                <div class="col-sm-8 col-md-8 col-md-offset-2">
                    <div class="panel panel-default">
                    <table class="table table-striped">
                        <label id="testing" style="display:none;">[[debit_credit]]</label>
                        <thead>
                            <th>Accounts Summary</th>
                        </thead>
                        <tbody>
                            <tr id="creditSummaryRow" style="border-radius: 15px;">
                                <td>Summary of Credit account:</td>
                                <td><div id="creditSummary">$[[amount]]</span></td>
                            </tr>
                            <tr id="debitSummaryRow">
                                <td>Summary of Debit account:</td>
                                <td><div id="debitSummary">$[[amount]]</span></td>
                            </tr>
                            <tr id="totalSummaryRow">
                                <td>Total:</td>
                                <td><div id="totalSummary">$[[amount]]</div></td>
                            </tr>
                        </tbody>
                    </table>
                    </div>
                </div>
                [[/account]]

            </div>
    </script>
    <div id='dynamic-area' class='dynamic-area'></div>


   
</body>

<script>
    $(document).ready(function() {

    	var raw_barcode;
    	var path = document.location.pathname;

    	console.log("Checking for url " + path);

		if(path.match(/\/account/)) {
			console.log("found the account");
			account = path.match(/\/account(.*)/)[1];
			raw_barcode = account.split('/');
			raw_barcode = raw_barcode[1];

			console.log("User barcode: " + raw_barcode);
			get_account(raw_barcode);

		}


    });

</script>

</html>

mysite/searcher/templates/searcher/close-form.html
{% load jstemplate %}

<html>
<head>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/reset.css">
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/index.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js"></script>
  	<script src="{{ STATIC_URL }}libs/mustache.js"></script>
  	<script src="{{ STATIC_URL }}libs/chart.min.js"></script>
  	<script type="text/javascript">
  		Mustache.tags = ['[[', ']]'];


    	function delete_account(){

    		$.ajax({
				url: "/close-account/",

				success: function(res) {

					console.log(res);
					console.log("form to delete");

					// Have all available data
					if ( res.status === 1 ) {

						var template = $('#account-template').html();
						console.log(html);
						console.log("delete time")
						$('#dynamic-area').html(html);


					}


					// No data at all for that fraction
					else {
						var template = $('#no-results-template').html();
						console.log(template);
						var html = Mustache.to_html(template);
						console.log(html);
						$('#dynamic-area').html(html);
					}

				}

			});
		}

  	</script>

	</head>


<body>
		<div class='form-header'> Close Account</div>

			<form action="{% url 'close_account' %}" method="POST" enctype="multipart/form-data">
			{% csrf_token %}

				<div class=''>
				   <label for="id_account_holder">Account holder:</label>
				   <input id="id_account_holder" type="text" class="" name="account_holder" />
				</div>

				<div class=''>
				   <label for="id_debit_credit">Debit or Credit:</label>
				   <input id="id_debit_credit" type="text" class="" name="debit_credit" />
				</div>

				<div class=''>
				   <label for="id_reason">Reason for closing acccount:</label>
				   <input id="id_reason" type="text" class="" name="reason" />
				</div>
				
				<div>
					<input type="submit" class="submit-close" value="Request Account Closing"/>
				</div>	


			</form>

	<div id='dynamic-area' class='dynamic-area'></div>



 <script>
    $(document).ready(function() {

    	var path = document.location.pathname;

    	console.log("Checking for url " + path);

		if(path.match(/\/close-account/)) {
			console.log("found the account");

			delete_account()
		}


    });
    
</script>


</body>
</html>

mysite/searcher/templates/searcher/login.html
{% block main %}
{% load staticfiles %}
<!DOCTYPE html>
<html>

<link href="{% static 'dist/css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'dist/css/Custom.css' %}" rel="stylesheet">
<script src="https://code.jquery.com/jquery.js"></script>
<script src="{% static 'dist/js/bootstrap.min.js' %}"></script>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django Unchained Banking App</title>
</head>

<body>

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="col-md-10"
            style="padding-left:0px;padding-top:10px;padding-bottom:10px;">
                <img 
                src="{% static 'dist/images/logo.jpg' %}"
                style = "height: 50px; width: 50px;"></img>
                <h3 style="display:inline;padding-left: 5px;">Django Unchained</h3>
            </div>
        </div>
    </div>
    <div class="row">
            <div class="col-sm-8 col-md-8 col-md-offset-2">
                <nav class="navbar navbar-default" role="navigation">
                    <ul class="nav nav-justified navbar-nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#">Offers</a></li>
                        <li><a href="#">Enroll</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </nav>
            </div>
    </div>


    <div class="row">
        <div class="col-sm-5 col-md-5 col-md-offset-2">
            <div id="mainCarousel" data-interval="5000" data-ride="carousel" class="carousel slide">
                <ol class="carousel-indicators">
                    <li data-target="#mainCarousel" data-slide-to="0"
                    class="active"></li>
                    <li data-target="#mainCarousel" data-slide-to="1"></li>
                    <li data-target="#mainCarousel" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <div class="carousel-caption">
                        <h1>Picture One</h1>
                        <p class="lead">This is some text.</p>
                        </div>
                    </div>

                    <div class="item">
                        <div class="carousel-caption">
                        <h1>Picture Two</h1>
                        <p class="lead">This is some other text.</p>
                        </div>
                    </div>

                    <div class="item">
                        <div class="carousel-caption">
                        <h1>Picture Three</h1>
                        <p class="lead">Last block of text.</p>
                        </div>
                    </div>
                </div>
                <a class="carousel-control left" href="#mainCarousel"
                data-slide="prev"><span class="glyphicon
                glyphicon-chevron-left"></span></a>
                <a class="right carousel-control" href="#mainCarousel"
                data-slide="next"><span class="glyphicon
                glyphicon-chevron-right"></span></a>
            </div>
        </div>
        
        <div class="col-sm-3 col-md-3">
             <h3>Welcome!</h3>
             <br>

             <form action="/login/" name="LoginForm" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username"
                    placeholder="Username">
                </div>

                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control"
                    id="password" name="password" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>

            <br>
            <p>Need an account? <a href="#">Enroll now</a></p>
        </div>
    </div> <!-- row -->

    <!-- An entire row/col structure for just a horizontal separator. Yup. -->
    <div class="row" style="padding-top:30px;padding-bottom:30px;">
        <div class="col-sm-4 col-md-4 col-md-offset-4">
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-8 col-md-8 col-md-offset-2">
            <div class="col-md-4" style="text-align:center;">
                <img class="img-circle"
                src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                alt = "Generic placeholder image" style="width: 140px; height:
                140px;">
                <h2>Promotion</h2>
                <p>Promotion text</p>
            </div>
            <div class="col-md-4" style="text-align:center;">
                <img class="img-circle"
                src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                alt = "Generic placeholder image" style="width: 140px; height:
                140px;">

                <h2>Second Promotion</h2>
                <p>Text to promote the second promotion</p>
            </div>
            <div class="col-md-4" style="text-align:center;">
                <img class="img-circle"
                src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                alt = "Generic placeholder image" style="width: 140px; height:
                140px;">

                <h2>Third Promotion</h2>
                <p>Text to promote the final promotion</p>
            </div>
        </div>
    </div>

    <div class="row" style="padding-top:30px;padding-bottom:30px;">
        <div class="col-sm-4 col-md-4 col-md-offset-4">
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-8 col-md-8 col-md-offset-2">
            <center>This is the misc. section where we put anything else</center>
        </div>
    </div>
    
</body>

</html>

{% endblock %}

mysite/searcher/templates/searcher/transfer-form.html
{% load jstemplate %}

<html>
<head>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/reset.css">
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/index.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js"></script>
  	<script src="{{ STATIC_URL }}libs/mustache.js"></script>
  	<script src="{{ STATIC_URL }}libs/chart.min.js"></script>
  	<script type="text/javascript">
  		Mustache.tags = ['[[', ']]'];


    	function delete_account(){

    		$.ajax({
				url: "/close-account/",

				success: function(res) {

					console.log(res);
					console.log("form to delete");

					// Have all available data
					if ( res.status === 1 ) {

						var template = $('#account-template').html();
						console.log(html);
						console.log("delete time")
						$('#dynamic-area').html(html);


					}


					// No data at all for that fraction
					else {
						var template = $('#no-results-template').html();
						console.log(template);
						var html = Mustache.to_html(template);
						console.log(html);
						$('#dynamic-area').html(html);
					}

				}

			});
		}

  	</script>

	</head>


<body>
		<div class='form-header'> Transfer Money</div>

			<form action="{% url 'transfer_money' %}" method="POST" enctype="multipart/form-data">
			{% csrf_token %}

				<div class=''>
				   <label for="id_account_holder">Account holder (routing number):</label>
				   <input id="id_account_holder" type="text" class="" name="account_holder" />
				</div>

				<div class=''>
				   <label for="id_debit_credit">Debit or Credit:</label>
				   <input id="id_debit_credit" type="text" class="" name="debit_credit" />
				</div>

				<div class=''>
				   <label for="id_amount_transfer">Amount:</label>
				   <input id="id_amount_transfer" type="text" class="" name="amount_transfer" />
				</div>				

				<div class=''>
				   <label for="id_reason">Add note:</label>
				   <input id="id_reason" type="text" class="" name="reason" />
				</div>

				<div class=''>
				   <label for="id_routing_number">Routing number (routing to?):</label>
				   <input id="id_routing_number" type="text" class="" name="routing_number" />
				</div>
				
				<div>
					<input type="submit" class="submit-close" value="Request Account Closing"/>
				</div>	


			</form>

	<div id='dynamic-area' class='dynamic-area'></div>



 <script>
    $(document).ready(function() {

    	var path = document.location.pathname;

    	console.log("Checking for url " + path);

		if(path.match(/\/close-account/)) {
			console.log("found the account");

			delete_account()
		}


    });
    
</script>


</body>
</html>